Add missing "raise"
Description:
Add missing "raise" keyword.  This defect was pointed out in an RFC
8032 Errata submitted by D. Bleichenbacher (2019-12-06) and verified
by C. Perkins (2021-05-24).  Add tests that check that the expected
exceptions are indeed raised.

Testing:
Before the missing "raise" keyword was added:

  $ python3 Section-6.py
  Traceback (most recent call last):
    File "Section-6.py", line 218, in <module>
      raise Exception("This exception should not be raised")
  Exception: This exception should not be raised

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "Section-6.py", line 220, in <module>
      assert(str(E) == "Bad signature length")
  AssertionError

After:

  $ python3 Section-6.py
  All tests passed.